name: quark
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - pandas=1.3.3
  - seaborn=0.11.2
  - pip=21.2.4
  - pip:
      - amazon-braket-ocean-plugin==1.0.5
      - pyqubo==1.0.13
      - qiskit==0.34.1
      - pyyaml==5.4.1
      - inquirer==2.7.0
